// Mocks generated by Mockito 5.3.0 from annotations
// in ncl_damonique/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ncl_damonique/models/cruise_ship_model.dart' as _i2;
import 'package:ncl_damonique/services/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCruiseShip_0 extends _i1.SmartFake implements _i2.CruiseShip {
  _FakeCruiseShip_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CruiseShip> getCruiseShip(_i2.CruiseShipName? shipName) =>
      (super.noSuchMethod(Invocation.method(#getCruiseShip, [shipName]),
              returnValue: _i4.Future<_i2.CruiseShip>.value(_FakeCruiseShip_0(
                  this, Invocation.method(#getCruiseShip, [shipName]))))
          as _i4.Future<_i2.CruiseShip>);
}
